# Generated by Django 3.0 on 2020-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='recurrence',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Anually', 'Anually')], max_length=200, null=True),
        ),
    ]
