# Generated by Django 3.0 on 2020-12-29 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_remove_plan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='customer',
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
