# Generated by Django 3.0 on 2020-12-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_plan_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='customer',
        ),
    ]
