# Generated by Django 3.0 on 2020-12-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201229_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='creator',
        ),
        migrations.AddField(
            model_name='plan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
    ]
