# Generated by Django 3.0 on 2020-12-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201229_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
