# Generated by Django 3.0 on 2020-12-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201229_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='tipo',
        ),
    ]
