# Generated by Django 3.0 on 2021-01-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201229_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
